const resList = [
  {
    id: "759796",
    name: "Go Zero Ice Creams & Desserts",
    image: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=400",
    locality: "Mahatma Phule Police Chowki",
    areaName: "Camp",
    costForTwo: "₹150 for two",
    cuisines: ["Ice Cream", "Desserts", "Healthy Food"],
    avgRating: 4.1,
    totalRatings: "163",
    veg: true,
    isOpen: true,
    deliveryTime: "20-25 mins",
    distance: "1.9 km",
    discount: { header: "70% OFF", subHeader: "UPTO ₹140" }
  },
  {
    id: "97301",
    name: "Ganesh Bhavan Sweets And Snacks",
    image: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400",
    locality: "Ghorpadi",
    areaName: "Ghorpadi",
    costForTwo: "₹100 for two",
    cuisines: ["Sweets", "Snacks"],
    avgRating: 4.4,
    totalRatings: "1.8K+",
    veg: true,
    isOpen: true,
    deliveryTime: "35-45 mins",
    distance: "3.0 km",
    discount: { header: "ITEMS", subHeader: "AT ₹19" }
  },
  {
    id: "8525",
    name: "Mad Over Donuts",
    image: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400",
    locality: "Kumar Pacific Mall",
    areaName: "Swargate",
    costForTwo: "₹200 for two",
    cuisines: ["Desserts", "Sweets", "Bakery"],
    avgRating: 4.4,
    totalRatings: "4.6K+",
    veg: true,
    isOpen: true,
    deliveryTime: "45-55 mins",
    distance: "4.7 km",
    discount: { header: "60% OFF", subHeader: "UPTO ₹120" }
  },
  {
    id: "402760",
    name: "Theobroma",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400",
    locality: "Camp",
    areaName: "Camp",
    costForTwo: "₹400 for two",
    cuisines: ["Bakery", "Desserts"],
    avgRating: 4.5,
    totalRatings: "2.7K+",
    veg: false,
    isOpen: true,
    deliveryTime: "20-25 mins",
    distance: "2.7 km",
    discount: { header: "ITEMS", subHeader: "AT ₹49" }
  },
  {
    id: "386176",
    name: "NIC Ice Creams",
    image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=400",
    locality: "Prabhat Road",
    areaName: "Shivaji Nagar",
    costForTwo: "₹120 for two",
    cuisines: ["Ice Cream", "Desserts"],
    avgRating: 4.6,
    totalRatings: "2.3K+",
    veg: true,
    isOpen: true,
    deliveryTime: "25-30 mins",
    distance: "2.8 km",
    discount: { header: "65% OFF", subHeader: "UPTO ₹130" }
  },
  {
    id: "508883",
    name: "The Belgian Waffle Co.",
    image: "https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=400",
    locality: "Ambedkar Road",
    areaName: "Camp Area",
    costForTwo: "₹200 for two",
    cuisines: ["Waffle", "Desserts", "Ice Cream"],
    avgRating: 4.7,
    totalRatings: "1.4K+",
    veg: true,
    isOpen: true,
    deliveryTime: "25-30 mins",
    distance: "1.7 km",
    discount: { header: "30% OFF", subHeader: "UPTO ₹60" }
  },
  {
    id: "100001",
    name: "Domino's Pizza",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400",
    locality: "FC Road",
    areaName: "Shivaji Nagar",
    costForTwo: "₹500 for two",
    cuisines: ["Pizza", "Italian", "Fast Food"],
    avgRating: 4.2,
    totalRatings: "5.1K+",
    veg: false,
    isOpen: true,
    deliveryTime: "30-35 mins",
    distance: "2.3 km",
    discount: { header: "50% OFF", subHeader: "UPTO ₹100" }
  },
  {
    id: "100002",
    name: "Vaishali Restaurant",
    image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=400",
    locality: "FC Road",
    areaName: "Deccan",
    costForTwo: "₹300 for two",
    cuisines: ["South Indian", "Chinese", "Fast Food"],
    avgRating: 4.5,
    totalRatings: "8.2K+",
    veg: true,
    isOpen: true,
    deliveryTime: "20-25 mins",
    distance: "1.5 km",
    discount: { header: "40% OFF", subHeader: "UPTO ₹80" }
  },
  {
    id: "100003",
    name: "Burger King",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400",
    locality: "JM Road",
    areaName: "Deccan",
    costForTwo: "₹400 for two",
    cuisines: ["Burgers", "Fast Food", "American"],
    avgRating: 4.0,
    totalRatings: "3.9K+",
    veg: false,
    isOpen: true,
    deliveryTime: "25-30 mins",
    distance: "3.1 km",
    discount: { header: "45% OFF", subHeader: "UPTO ₹90" }
  },
  {
    id: "100004",
    name: "Wow! Momo",
    image: "https://images.unsplash.com/photo-1541833276-0c11cd50e177?w=400",
    locality: "Koregaon Park",
    areaName: "Koregaon Park",
    costForTwo: "₹250 for two",
    cuisines: ["Chinese", "Tibetan", "Momos"],
    avgRating: 4.3,
    totalRatings: "2.9K+",
    veg: false,
    isOpen: true,
    deliveryTime: "20-25 mins",
    distance: "2.0 km",
    discount: { header: "35% OFF", subHeader: "UPTO ₹70" }
  },
  {
    id: "100005",
    name: "Sagar Ratna",
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400",
    locality: "Aundh",
    areaName: "Aundh",
    costForTwo: "₹350 for two",
    cuisines: ["South Indian", "North Indian"],
    avgRating: 4.4,
    totalRatings: "6.5K+",
    veg: true,
    isOpen: true,
    deliveryTime: "30-35 mins",
    distance: "4.2 km",
    discount: { header: "20% OFF", subHeader: "UPTO ₹50" }
  },
  {
    id: "100006",
    name: "Barbeque Nation",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=400",
    locality: "Viman Nagar",
    areaName: "Viman Nagar",
    costForTwo: "₹900 for two",
    cuisines: ["North Indian", "BBQ", "Buffet"],
    avgRating: 4.6,
    totalRatings: "9.1K+",
    veg: false,
    isOpen: true,
    deliveryTime: "40-45 mins",
    distance: "5.5 km",
    discount: { header: "10% OFF", subHeader: "UPTO ₹100" }
  },
  {
    id: "100007",
    name: "Chaitanya Parathas",
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=400",
    locality: "Karve Road",
    areaName: "Kothrud",
    costForTwo: "₹200 for two",
    cuisines: ["North Indian", "Parathas"],
    avgRating: 4.3,
    totalRatings: "1.2K+",
    veg: true,
    isOpen: true,
    deliveryTime: "25-30 mins",
    distance: "3.4 km",
    discount: { header: "25% OFF", subHeader: "UPTO ₹60" }
  },
  {
    id: "100008",
    name: "KFC",
    image: "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=400",
    locality: "Baner Road",
    areaName: "Baner",
    costForTwo: "₹450 for two",
    cuisines: ["Fried Chicken", "Fast Food"],
    avgRating: 4.1,
    totalRatings: "4.4K+",
    veg: false,
    isOpen: true,
    deliveryTime: "30-35 mins",
    distance: "6.0 km",
    discount: { header: "50% OFF", subHeader: "UPTO ₹120" }
  },
  {
    id: "100009",
    name: "Cafe Goodluck",
    image: "https://images.unsplash.com/photo-1600093463592-8e36ae95ef56?w=400",
    locality: "Deccan Gymkhana",
    areaName: "Deccan",
    costForTwo: "₹300 for two",
    cuisines: ["Iranian", "Bakery", "Cafe"],
    avgRating: 4.5,
    totalRatings: "3.3K+",
    veg: false,
    isOpen: true,
    deliveryTime: "20-25 mins",
    distance: "1.8 km",
    discount: { header: "30% OFF", subHeader: "UPTO ₹70" }
  }
];

export default resList;